# Generated by Django 5.0.4 on 2024-04-15 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='my_email',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='my_username',
        ),
    ]
