# Generated by Django 5.0.4 on 2024-04-15 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_email_profile_my_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='my_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='my_username',
            new_name='username',
        ),
    ]
